language: scala

branches:
  only:
  - master

scala:
  - 2.12.6
jdk:
  - oraclejdk8

sudo: required

services:
#  - mysql
  - docker

#addons:
#  apt:
#    sources:
#    - mysql-5.7-trusty
#    packages:
#    - mysql-server

env:
  - JAVA_OPTS="-Dsbt.log.noformat=true"

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.dodo
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

before_install:
  - sudo service mysql stop
  - docker pull mysql:8.0.3
  - docker run -d -p 127.0.0.1:3306:3306 --name mysqld -e MYSQL_DATABASE=cactacea -e MYSQL_USER=cactacea -e MYSQL_PASSWORD=cactacea -e MYSQL_ROOT_PASSWORD=root mysql:8.0.3 --innodb_log_file_size=256MB --innodb_buffer_pool_size=512MB --max_allowed_packet=16MB --local-infile=1 --character-set-server=utf8 --collation-server=utf8_unicode_ci

script:
  - export CODACY_PROJECT_TOKEN=272e483af831425ba3d30673b81281ef
  - sbt codacyCoverage
  - sbt ++$TRAVIS_SCALA_VERSION clean test coverage coverageReport coverageAggregate
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
