language: scala

branches:
  only:
  - master

scala:
  - 2.12.6
jdk:
  - oraclejdk8

sudo: required

services:
  - mysql
  - docker

addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server

env:
  - JAVA_OPTS="-Dsbt.log.noformat=true"

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.dodo
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

before_install:
  - sudo mysql -e "create database if not exists cactacea;"
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -proot
  - sudo service mysql restart

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test coverage coverageReport coverageAggregate
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
  - export CODACY_PROJECT_TOKEN=272e483af831425ba3d30673b81281ef
  - sbt codacyCoverage
