language: scala

branches:
  only:
  - master

scala:
  - 2.12.4
jdk:
  - oraclejdk8

sudo: required

services:
  - mysql
  - docker

env:
  - JAVA_OPTS="-Dsbt.log.noformat=true"

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
   - $HOME/.dodo

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

before_install:
  - chmod +x ./scripts/*.sh
  - bash ./scripts/travis_mysql_5.7.sh
  - bash ./scripts/travis_minio.sh
  - bash ./scripts/travis_mysql-reset-root-password.sh

script:
  - bash ./scripts/travis_db_migrate.sh
  - sbt "set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)" coverage test coverageReport
  - sbt coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
