version: 0.2

env:
  variables:
    CONF: "prod.conf"

phases:
  install:
    commands:
      - echo "$(lsb_release -cs)"
      - sudo apt-get update -y
      - sudo apt-get install -y apt-transport-https ca-certificates software-properties-common
      - sudo add-apt-repository -y ppa:openjdk-r/ppa
      - sudo apt-get remove -y openjdk-9-*
      - sudo apt-get install -y openjdk-8-jdk

      - sudo update-ca-certificates -f
      - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
      - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      - sudo apt-get update -y
      - sudo apt-get install -y sbt
      - export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8

      - sudo pip install --upgrade awscli

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"
  build:
    commands:
      - sbt compile
      - sbt demo/docker:publish
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - Dockerrun.aws.json
