-- MySQL Script generated by MySQL Workbench
-- Fri Sep  6 13:55:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ${schema}
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ${schema}
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `${schema}` DEFAULT CHARACTER SET utf8 ;
USE `${schema}` ;

-- -----------------------------------------------------
-- Table `${schema}`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`members` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `communication_type` TINYINT(4) NOT NULL,
  `user_id` BIGINT(20) NULL,
  `email` VARCHAR(256) NULL,
  `phone_no` VARCHAR(20) NULL,
  `registered_at` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`cards` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `medium_id` BIGINT(20) NOT NULL,
  `by` BIGINT(20) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  INDEX `fk_cards_members_idx` (`by` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cards_members`
    FOREIGN KEY (`by`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`groups` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `member_count` BIGINT(20) NOT NULL,
  `by` BIGINT(20) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groups_members1_idx` (`by` ASC),
  CONSTRAINT `fk_groups_members1`
    FOREIGN KEY (`by`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`adjustments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`adjustments` (
  `id` BIGINT(20) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  `by` BIGINT(20) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adjustments_members1_idx` (`by` ASC),
  INDEX `fk_adjustments_groups1_idx` (`group_id` ASC),
  CONSTRAINT `fk_adjustments_members1`
    FOREIGN KEY (`by`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adjustments_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `${schema}`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`positions` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `authority_type` TINYINT(4) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  `by` BIGINT(20) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  INDEX `fk_positions_groups1_idx` (`group_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_positions_members1_idx` (`by` ASC),
  CONSTRAINT `fk_positions_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `${schema}`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_positions_members1`
    FOREIGN KEY (`by`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`tasks` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  `by` BIGINT(20) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_members1_idx` (`by` ASC),
  INDEX `fk_tasks_groups1_idx` (`group_id` ASC),
  CONSTRAINT `fk_tasks_members1`
    FOREIGN KEY (`by`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `${schema}`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`events` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `latlng` VARCHAR(10) NULL,
  `adjustment_id` BIGINT(20) NULL,
  `task_id` BIGINT(20) NULL,
  `channel_id` BIGINT(20) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  `by` BIGINT(20) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_groups1_idx` (`group_id` ASC),
  INDEX `fk_events_adjustments1_idx` (`adjustment_id` ASC),
  INDEX `fk_events_tasks1_idx` (`task_id` ASC),
  INDEX `fk_events_members1_idx` (`by` ASC),
  CONSTRAINT `fk_events_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `${schema}`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_adjustments1`
    FOREIGN KEY (`adjustment_id`)
    REFERENCES `${schema}`.`adjustments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_tasks1`
    FOREIGN KEY (`task_id`)
    REFERENCES `${schema}`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_members1`
    FOREIGN KEY (`by`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`task_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`task_Items` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `person_assigned` VARCHAR(200) NOT NULL,
  `status` TINYINT(4) NOT NULL,
  `task_id` BIGINT(20) NOT NULL,
  `by` BIGINT(20) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_Items_tasks1_idx` (`task_id` ASC),
  INDEX `fk_task_Items_members1_idx` (`by` ASC),
  CONSTRAINT `fk_task_Items_tasks1`
    FOREIGN KEY (`task_id`)
    REFERENCES `${schema}`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_Items_members1`
    FOREIGN KEY (`by`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`event_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`event_members` (
  `event_id` BIGINT(20) NOT NULL,
  `member_id` BIGINT(20) NOT NULL,
  `join_type` TINYINT(4) NOT NULL,
  INDEX `fk_event_members_events1_idx` (`event_id` ASC),
  INDEX `fk_event_members_members1_idx` (`member_id` ASC),
  UNIQUE INDEX `event_members_UNIQUE` (`event_id` ASC, `member_id` ASC),
  CONSTRAINT `fk_event_members_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `${schema}`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_members_members1`
    FOREIGN KEY (`member_id`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`group_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`group_members` (
  `group_id` BIGINT(20) NOT NULL,
  `member_id` BIGINT(20) NOT NULL,
  `position_id` BIGINT(20) NOT NULL,
  `joined_at` BIGINT(20) NOT NULL,
  INDEX `fk_group_members_groups1_idx` (`group_id` ASC),
  INDEX `fk_group_members_members1_idx` (`member_id` ASC),
  INDEX `fk_group_members_positions1_idx` (`position_id` ASC),
  UNIQUE INDEX `group_members_UNIQUE` (`group_id` ASC, `member_id` ASC),
  CONSTRAINT `fk_group_members_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `${schema}`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_members_members1`
    FOREIGN KEY (`member_id`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_members_positions1`
    FOREIGN KEY (`position_id`)
    REFERENCES `${schema}`.`positions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`card_exchanges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`card_exchanges` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `member_id` BIGINT(20) NOT NULL,
  `card_id` BIGINT(20) NOT NULL,
  `by` BIGINT(20) NOT NULL,
  `exchanged_at` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_card_exchanges_members1_idx` (`member_id` ASC),
  INDEX `fk_card_exchanges_cards1_idx` (`card_id` ASC),
  INDEX `fk_card_exchanges_members2_idx` (`by` ASC),
  CONSTRAINT `fk_card_exchanges_members1`
    FOREIGN KEY (`member_id`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_card_exchanges_cards1`
    FOREIGN KEY (`card_id`)
    REFERENCES `${schema}`.`cards` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_card_exchanges_members2`
    FOREIGN KEY (`by`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`event_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`event_schedules` (
  `event_id` BIGINT(20) NOT NULL,
  `schedule_date` BIGINT(20) NOT NULL,
  INDEX `fk_event_schedules_events1_idx` (`event_id` ASC),
  UNIQUE INDEX `event_schedules_UNIQUE` (`event_id` ASC, `schedule_date` ASC),
  CONSTRAINT `fk_table1_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `${schema}`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`adjustment_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`adjustment_members` (
  `adjustment_id` BIGINT(20) NOT NULL,
  `member_id` BIGINT(20) NOT NULL,
  `comment` VARCHAR(200) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  INDEX `fk_adjustment_members_adjustments1_idx` (`adjustment_id` ASC),
  INDEX `fk_adjustment_members_members1_idx` (`member_id` ASC),
  UNIQUE INDEX `adjustment_membes_UNIQUE` (`adjustment_id` ASC, `member_id` ASC),
  CONSTRAINT `fk_adjustment_members_adjustments1`
    FOREIGN KEY (`adjustment_id`)
    REFERENCES `${schema}`.`adjustments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adjustment_members_members1`
    FOREIGN KEY (`member_id`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`adjustment_times`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`adjustment_times` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `adjustment_id` BIGINT(20) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adjustment_times_adjustments1_idx` (`adjustment_id` ASC),
  CONSTRAINT `fk_adjustment_times_adjustments1`
    FOREIGN KEY (`adjustment_id`)
    REFERENCES `${schema}`.`adjustments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`adjustment_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`adjustment_answers` (
  `adjustment_id` BIGINT(20) NOT NULL,
  `adjustment_time_id` BIGINT(20) NOT NULL,
  `member_id` BIGINT(20) NOT NULL,
  `answer` TINYINT(4) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  INDEX `fk_adjustment_answers_adjustments1_idx` (`adjustment_id` ASC),
  INDEX `fk_adjustment_answers_adjustment_times1_idx` (`adjustment_time_id` ASC),
  INDEX `fk_adjustment_answers_members1_idx` (`member_id` ASC),
  UNIQUE INDEX `adjustment_answers_UNIQUE` (`adjustment_id` ASC, `adjustment_time_id` ASC, `member_id` ASC),
  CONSTRAINT `fk_adjustment_answers_adjustments1`
    FOREIGN KEY (`adjustment_id`)
    REFERENCES `${schema}`.`adjustments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adjustment_answers_adjustment_times1`
    FOREIGN KEY (`adjustment_time_id`)
    REFERENCES `${schema}`.`adjustment_times` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adjustment_answers_members1`
    FOREIGN KEY (`member_id`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`surveys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`surveys` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `survey_type` TINYINT(4) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  `by` BIGINT(20) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_surveys_groups1_idx` (`group_id` ASC),
  INDEX `fk_surveys_members1_idx` (`by` ASC),
  CONSTRAINT `fk_surveys_groups1`
    FOREIGN KEY (`group_id`)
    REFERENCES `${schema}`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surveys_members1`
    FOREIGN KEY (`by`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`survey_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`survey_questions` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(200) NOT NULL,
  `survey_id` BIGINT(20) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_survey_questions_surveys1_idx` (`survey_id` ASC),
  CONSTRAINT `fk_survey_questions_surveys1`
    FOREIGN KEY (`survey_id`)
    REFERENCES `${schema}`.`surveys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `${schema}`.`survey_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `${schema}`.`survey_answers` (
  `surveys_id` BIGINT(20) NOT NULL,
  `survey_questions_id` BIGINT(20) NOT NULL,
  `members_id` BIGINT(20) NOT NULL,
  `checked` TINYINT(1) NOT NULL,
  `created_at` BIGINT(20) NOT NULL,
  INDEX `fk_survey_answers_surveys1_idx` (`surveys_id` ASC),
  INDEX `fk_survey_answers_survey_questions1_idx` (`survey_questions_id` ASC),
  INDEX `fk_survey_answers_members1_idx` (`members_id` ASC),
  CONSTRAINT `fk_survey_answers_surveys1`
    FOREIGN KEY (`surveys_id`)
    REFERENCES `${schema}`.`surveys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_survey_answers_survey_questions1`
    FOREIGN KEY (`survey_questions_id`)
    REFERENCES `${schema}`.`survey_questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_survey_answers_members1`
    FOREIGN KEY (`members_id`)
    REFERENCES `${schema}`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
